- phase_cli/cmd/auth.py
Updates the webauth url to use route params instead of url fragments. 
Related to:https://github.com/phasehq/console/pull/97/commits/191166d5efccd8baba97c1e07c275e876e1c93d1
> fix: update console url for webauth

- install.sh
This fixes the chmod errors in the temp directories on linux binary installs.
> fix: fixed install_from_binary() chmod errors

- phase_cli/cmd/secrets/create.py
- phase_cli/cmd/secrets/export.py
- phase_cli/cmd/secrets/update.py
- phase_cli/main.py
- phase_cli/utils/crypto.py
- phase_cli/utils/misc.py
This change introduces the ability to create secrets for the following `phase secrets` sub commands:
- create 
- update
The following secrets types are currently supported:
- Alphanumeric
- Hex
- Base64
- Base64 URL safe
- key128 : 16 Byte high entropy base64 encoded symmetric key - suitable for AES-128
- key256 : 32 Byte high entropy base64 encoded symmetric key  - suitable for use with ChaCha20 or AES-256
For alphanumeric, base64, base64urlsafe and hex - the length can also be set by passing `--length` flag and can vary from 1 to 256. 
Examples:
```fish
phase secrets create RAND --random alphanumeric --length 256
KEY 🗝️                        | VALUE ✨                                                             
---------------------------------------------------------------------------- …
```
> Generate secrets

- .github/workflows/build_release.yml
- dev-requirements.txt
- phase_cli/cmd/secrets/export.py
- phase_cli/main.py
- phase_cli/utils/const.py
- tests/secrets_export.py
- dotenv (.env): Key-value pairs in a simple text format.
- JSON: JavaScript Object Notation, useful for integration with various tools and languages.
- CSV: Comma-Separated Values, a simple text format for tabular data.
- YAML: Human-readable data serialization format, often used for configuration files.
- XML: Extensible Markup Language, suitable for complex data structures.
- TOML: Tom's Obvious, Minimal Language, a readable configuration file format.
- HCL: HashiCorp Configuration Language, used in HashiCorp tools like Terraform.
- INI: A simple format often used for configuration files.
- Java Properties: Key-value pair format commonly used in Java applications.
```fish
Securely manage and sync environment variables with Phase.
⢠⠔⠋⣳⣖⠚⣲⢖⠙⠳⡄                          
⡴⠉⢀⡼⠃⢘⣞⠁⠙⡆ ⠘⡆ …
```
> Feat  export formats

- .github/workflows/build_release.yml
- APKBUILD
- dev-requirements.txt
- phase_cli/cmd/run.py
- phase_cli/cmd/secrets/create.py
- phase_cli/cmd/secrets/delete.py
- phase_cli/cmd/secrets/export.py
- phase_cli/cmd/secrets/get.py
- phase_cli/cmd/secrets/import_env.py
- phase_cli/cmd/secrets/list.py
- phase_cli/cmd/secrets/update.py
- phase_cli/main.py
- phase_cli/utils/const.py
- phase_cli/utils/misc.py
- phase_cli/utils/phase_io.py
- requirements.txt
- tests/secrets_export.py
- tests/tags.py
Tags 🏷️: Comma-separated list of tags to filter the secrets. Tags are case-insensitive and support partial matching. For example, using --tags "prod,config" will include secrets tagged with "Production" or "ConfigData". Underscores in tags are treated as spaces, so "prod_data" matches "prod data".
Additional changes:
- Added support for comments
- Get now returns secrets in json
```fish
λ phase secrets get POSTGRES_CONNECTION_STRING --tags prod
{
"key": "POSTGRES_CONNECTION_STRING",
"value": "postgresql://${production.DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}",
"overridden": false,
"tags": [
"PROD"
],
"comment": "AWS RDS HA 848543535353"
}
```
- Refactored table rendering logic for phase secrets list
- use `rich.console` for logging errors
> Feat  tags comments

- APKBUILD
- phase_cli/cmd/run.py
- phase_cli/utils/const.py
This PR fixes `list index out of range` error when referring a non existing secret in a valid cross environment.
Example:
Secret: DEBUG_PROD - doesn't exist
Environment: production - exits
Secret: DEBUG - exits and set to ${production.DEBUG_PROD}
Environment: development - exists
```fish
λ phase run --env development "printenv | grep DEBUG"
[15:05:42] ⚠️  Warning: Secret 'DEBUG_PROD' not found in environment 'production'. Ignoring...                                                                            
DEBUG=
```
> Fix  cross env edge case

- phase_cli/cmd/secrets/create.py
- phase_cli/cmd/users/whoami.py
- phase_cli/main.py
- phase_cli/utils/misc.py
Use unicode hair space `\u200A` instead of ' ` '  to space emojies.
Needs testing on:
- Windows (powershell, bash, gitbash, WSL etc.)
- MacOS terminal
> feat: use \u200A to space emoji unicode instead of '`'

- phase_cli/exceptions.py
- phase_cli/utils/misc.py
- phase_cli/utils/secret_referencing.py
* Throw an `EnvironmentNotFound` exception when the named environment is not found or cannot be accessed
* Return a secret value as is, if a reference cannot be resolved
> fix: resolver fallback behavior

- APKBUILD
- phase_cli/cmd/secrets/export.py
- phase_cli/utils/const.py
This PR reverts the previous decision to add a spinner and secret export stats. So commands like `docker run --rm --env-file <(phase secrets export --app application) alpine:latest printenv` are not broken.
> fix: removed progress spinner and export status

- APKBUILD
- phase_cli/cmd/auth.py
- phase_cli/cmd/users/logout.py
- phase_cli/cmd/users/switch.py
- phase_cli/cmd/users/whoami.py
- phase_cli/main.py
- phase_cli/utils/const.py
- phase_cli/utils/misc.py
This PR adds the ability to authenticate seamlessly switch between different Phase users, organizations and instances.
Notes: 
- Make sure you log out the Phase CLI before testing (phase users logout --purge)
- Make sure you are running https://github.com/phasehq/console/pull/211 version of the Phase Console
Things to test:
- Authentication: phase auth (log into different users, orgs instances)
- Switch users: phase users switch (switch in between them)
- phase secrets CRUD (test access to secrets)
> Added multiple users, organizations and instance support

- install.sh
This PR adds support aarch64 install support to the Phase CLI installation script. It is now possible to install the CLI on a raspberry pi 4 by simply running the script.
> feat: added aarch64 cli install support

- APKBUILD
- phase_cli/cmd/init.py
- phase_cli/utils/const.py
This PR improved phase init sub command.
Improvements:
- Print UUIDs along with name in application selection menu to easily distinguish between applications sharing a name
- Added a default environment selection which follows app selection
- Store `envId` in phase config (.phase.json) and bump the version to 2 
Fixes:
- No development environment found: https://github.com/phasehq/cli/issues/113
> Improve init

- APKBUILD
- phase_cli/cmd/open_console.py
- phase_cli/utils/const.py
- phase_cli/utils/misc.py
The `phase console` command now will follow the following behavior:
- If no phase config (phase.json) is present - simply open the PHASE_HOST
- If a phase config (.phase.json) v1 is present - open the application environments windows
- If a phase config (.phase.json) v2 is present - open the default application environments secret screen
Partially depends on: https://github.com/phasehq/cli/pull/132 which introduces phase config v2.
> Improve console

- APKBUILD
- phase_cli/utils/const.py
- phase_cli/utils/misc.py
> Fix: secret values from overflowing in the table

- APKBUILD
- phase_cli/utils/const.py
- phase_cli/utils/phase_io.py
This PR fixes an issue where the value of personal secrets was not being returned in the following commands:
- phase run
- phase secrets list
- phase secrets export
- phase secrets get
How to test:
- Activate personal secret override in the Phase Console and retrieve the secrets via the Phase CLI and check the value 
- De-activate personal secret override (while a value is saved) in he Phase Console and retrieve the secrets via the Phase CLI and check the value
> Fix: personal secret overrides

- APKBUILD
- phase_cli/cmd/secrets/create.py
- phase_cli/cmd/secrets/update.py
- phase_cli/main.py
- phase_cli/utils/const.py
- phase_cli/utils/network.py
This PR make the following changes and improvements:
- Replace blank spaces with underscores of the keys passed to `phase secrets update` and `phase secrets create`. fixed: https://github.com/phasehq/cli/issues/131
- Removed client side checks via phase.get to see weather a secret already exists in  `phase secrets update` and `phase secrets create`
- Print the actual error returned by the Phase API even if `PHASE_DEBUG` is `False`
- Improved of parsing the error messages from the Phase API
> Improve secret key processing

- .github/workflows/build_release.yml
This PR makes the following changes:
- Make sure macos-amd64 binary is being built on a intel based macos instance. 
- Add a macos-am64 build on macos-14 GitHub action image: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
- Parse the build and process the amd64 and arm64 packages as .zips in Process assets
> fix: macos builds

- phase_cli/cmd/run.py
- tests/phase_run.py
- tests/secret_referencing.py
- removed redundant tag filtering logic in phase run, handle tag in phase.get() instead (to be consistent with phase secrets export)
- added unit test for phase run
> Improved phase run and added tests

- APKBUILD
- phase_cli/cmd/secrets/create.py
- phase_cli/cmd/secrets/update.py
- phase_cli/main.py
- phase_cli/utils/const.py
- phase_cli/utils/phase_io.py
**PR Description:**
This PR adds personal secret override support to the CLI. Previously to toggle or set a personal value to a secret a user would have to go to the Phase Console, this change makes it more convenient as well as makes is easy to script automations using the CLI.
1. **Override Update:**
- Modified the `update` method to ensure that the personal override value is updated when the `--override` flag is used.
- Ensured that the shared secret value is updated only when the `--override` flag is not set.
2. **Toggle Override:**
- Implemented the `--toggle-override` functionality to toggle the `isActive` state for personal overrides during updates.
- Added logic to handle the toggle operation correctly.
3. **Command Updates:**
- Updated the `create` and `update` commands to …
> Feat: secret override support

- phase_cli/utils/secret_referencing.py
This PR addresses two key issues in our secret referencing implementation:
1. Fixes the handling of local path secret references, ensuring that secrets like `${folderlocal/SECRET_1}` are correctly resolved from Phase when not found in the local `secrets_dict`.
2. Improves the behavior for missing local paths, ensuring that the original reference is returned when a specified path is not found, which aligns with our test expectations.
- Modified the `resolve_secret_reference` function in `secret_referencing.py` to:
- Only fall back to the root path for local references if the original path was the root path ("/").
- Maintain the original behavior for cross-environment references.
- Improve error handling and fallback logic for missing secrets.
To test the local path secret referencing:
1. …
> Fix: Local Path Secret Referencing

- .github/workflows/build.yml
- .github/workflows/version.yml
- APKBUILD
- phase_cli/cmd/run.py
- phase_cli/cmd/secrets/create.py
- phase_cli/cmd/secrets/delete.py
- phase_cli/cmd/secrets/export.py
- phase_cli/cmd/secrets/get.py
- phase_cli/cmd/secrets/import_env.py
- phase_cli/cmd/secrets/list.py
- phase_cli/cmd/secrets/update.py
- phase_cli/main.py
- phase_cli/utils/const.py
- phase_cli/utils/misc.py
- phase_cli/utils/phase_io.py
- tests/phase_run.py
This PR adds the ability to directly specify an application ID using the `--app-id` flag across the following commands:
phase secrets:
- create
- get
- update
- delete
- list
- export
- import
phase:
- run
This feature allows users to bypass name-based application lookup, making the CLI more robust when dealing with applications that might have similar names.
- Added `--app-id` flag support to all relevant commands:
- `phase run`
- `phase secrets create/update/delete/list/get/import/export`
- Modified `phase_get_context` to prioritize `app_id` over `app_name` when both are provided
- Updated test suite to verify app ID functionality
```fish
phase secrets list --app-id dc371163-6735-49d2-a25a-2ce0fc3e147d --env dev
phase secrets get SECRET_KEY --app "MyApp" --app-id …
```
> Feat: add --app-id flag

- phase_cli/cmd/init.py
- phase_cli/cmd/open_console.py
- phase_cli/utils/misc.py
- tests/test_misc.py
This PR adds monorepo support to the Phase CLI. Users can now Phase config context inside of _n_ number of sub-directories. 
Ref: https://github.com/phasehq/cli/issues/183
When users run `phase init` they will be asked if they want to enabled monorepo support:
```bash
phase init      
? Select an App: example-app (7d8169ad-f15c-4517-b307-0b5f45099c6b)
? Choose a Default Environment: Development
? 🍱 Monorepo support: Would you like this configuration to apply to subdirectories? (y/N)
```
If they select Yes, the `.phase.json` config will be initialize with `"monorepoSupport": null`. The Phase CLI will for scan parent directories containing a `.phase.json` config with monorepo enabled, if one is found that config will be used. By default the CLI will search for the config in parent …
> feat: mono repo support

- setup.py
Addresses: https://github.com/phasehq/cli/issues/180
> fix: use snake case to comply with pypi naming convention

- phase_cli/cmd/open_console.py
- phase_cli/cmd/open_docs.py
- phase_cli/cmd/run.py
- phase_cli/cmd/secrets/create.py
- phase_cli/cmd/secrets/delete.py
- phase_cli/cmd/secrets/export.py
- phase_cli/cmd/secrets/get.py
- phase_cli/cmd/secrets/import_env.py
- phase_cli/cmd/secrets/list.py
- phase_cli/cmd/secrets/update.py
- phase_cli/cmd/update.py
- phase_cli/cmd/users/keyring.py
- phase_cli/cmd/users/switch.py
- phase_cli/cmd/users/whoami.py
- phase_cli/main.py
- tests/phase_run.py
- tests/secrets_export.py
- tests/secrets_get.py
This PR improves the way the Phase CLI handles exceptions and returns exit codes. This improves the scriptability of the CLI and improves it's operations in containerized environments.
Ref: https://github.com/phasehq/cli/issues/184
Before: 
```bash
phase secrets get A_SECRET_THAT_DOESNT_EXIST && echo $?
[15:07:37] 🔍 Secret not found...
0
```
After:
```bash
phase secrets get A_SECRET_THAT_DOESNT_EXIST && echo $?
[15:08:22] 🔍 Secret not found...
1
```
Changes made:
- Added / fixed error code statuses for the following commands:
- phase run
- phase secrets get
- phase secrets export
- phase secrets import
- phase secrets list
- phase secrets create
- phase secrets update
- phase secrets delete
- phase console
- phase update
- phase docs
- phase users
- phase users keyring
- phase users …
> feat: cli command error codes

- APKBUILD
- phase_cli/cmd/auth.py
- phase_cli/cmd/init.py
- phase_cli/utils/const.py
- phase_cli/utils/network.py
Fixes https://github.com/phasehq/console/issues/569.
This PR extends the existing utils for exception handling in `network.py` by catching cases of non-JSON responses from the Phase API.
Before the fix:
```fish
phase secrets list
[14:53:27] Error: Expecting value: line 1 column 1 (char 0)   
```
After the fix:
```fish
phase secrets list
[14:30:16] Error: 🗿 Unexpected response received from the Phase API. Please set PHASE_DEBUG=True to see the error & response.           main.py:344 
```
Response preview when DEBUG is set to True
```fish
export PHASE_DEBUG=True
~/git/phase/cli main* ❯ phase secrets list     
Traceback (most recent call last):
File "/home/nimish/git/phase/console/.conda/lib/python3.11/site-packages/requests/models.py", line 974, in json
return complexjson.loads(self.text, …
```
> feat: add error handling for JSON decode issues in API responses

- APKBUILD
- process_assets.py
- Group all phase cli dependencies in a managed vendor directory to avoid conflicts with other python packages
- Fixed process assets script to pick up alpine arm64 assets
Addresses: https://github.com/phasehq/cli/issues/241
> fix: alpine dependency conflicts

- APKBUILD
- README.md
- phase_cli/cmd/run.py
- phase_cli/cmd/shell.py
- phase_cli/cmd/update.py
- phase_cli/utils/const.py
- phase_cli/utils/misc.py
This PR fixes with how the Phase CLI would start other processes or application for the purposes of opening a web browser, updating the CLI to the latest version, injecting secrets into applications etc., with certain flags that were passing PyInstaller specific contexts via the `LD_LIBRARY_PATH` and or the `DYLD_LIBRARY_PATH` environment variable, which caused the resulting process or the application to have inconsistent contexts of certain dependencies such as OpenSSL. This fix simply filters them out. This PR also contains a small improvements in exception handling for the phase update` command.
More details can be found at: https://github.com/pyinstaller/pyinstaller/blob/34508a2cda1072718a81ef1d5a660ce89e62d295/doc/common-issues-and-pitfalls.rst#linux-and-unix-like-oses
Fixes: …
> fix: execute programs in a clean environment

- APKBUILD
- phase_cli/utils/const.py
- phase_cli/utils/secret_referencing.py
- tests/secret_referencing.py
- tests/test_secret_referencing_extended.py
This PR improves secret referencing resolution performance by using a client-side in-memory cache, fetching secrets in parallel and significantly reducing the number of API calls made to the Phase API. This dramatic reduction in API calls would mean fewer run-ins with API rate limits and further reduction of the number of secret audit logs being generated. Added recursive secret resolution support and extended partial env name matching logic. 
This is especially helpful for users with larger number of cross application referenced secrets (very often more than 100+ secrets) for use cases involving the user of another applications environment as a shared or common application.
Benchmarks: 
Example application and environment structure.
```tf
terraform {
required_providers {
phase = {
source …
```
> feat: optimize secret referencing performance
